/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_SetDisplay */

#ifndef _Included_com_dhk_io_SetDisplay
#define _Included_com_dhk_io_SetDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhk_io_SetDisplay
 * Method:    setDisplay
 * Signature: (Ljava/lang/String;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_SetDisplay_setDisplay
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_dhk_io_SetDisplay
 * Method:    setOrientation
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_SetDisplay_setOrientation
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
