/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_SystemTrayIcon */

#ifndef _Included_com_dhk_io_SystemTrayIcon
#define _Included_com_dhk_io_SystemTrayIcon
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dhk_io_SystemTrayIcon_DEFAULT_ICON_SIZE
#define com_dhk_io_SystemTrayIcon_DEFAULT_ICON_SIZE 16L
/*
 * Class:     com_dhk_io_SystemTrayIcon
 * Method:    nativeStart
 * Signature: (Ljava/lang/String;[III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dhk_io_SystemTrayIcon_nativeStart
  (JNIEnv *, jobject, jstring, jintArray, jint, jint);

/*
 * Class:     com_dhk_io_SystemTrayIcon
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_SystemTrayIcon_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_SystemTrayIcon
 * Method:    nativeSetIcon
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_SystemTrayIcon_nativeSetIcon
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_dhk_io_SystemTrayIcon
 * Method:    nativeSetVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_SystemTrayIcon_nativeSetVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_dhk_io_SystemTrayIcon
 * Method:    nativeGetIconSize
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_dhk_io_SystemTrayIcon_nativeGetIconSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
