/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_EnumDisplayModes */

#ifndef _Included_com_dhk_io_EnumDisplayModes
#define _Included_com_dhk_io_EnumDisplayModes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhk_io_EnumDisplayModes
 * Method:    enumDisplayModes
 * Signature: (Ljava/lang/String;)[Ljava/awt/DisplayMode;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dhk_io_EnumDisplayModes_enumDisplayModes
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
