/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_GetDisplay */

#ifndef _Included_com_dhk_io_GetDisplay
#define _Included_com_dhk_io_GetDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    enumDisplayModes
 * Signature: (Ljava/lang/String;)[Ljava/awt/DisplayMode;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dhk_io_GetDisplay_enumDisplayModes
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    queryNumOfConnectedDisplays
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dhk_io_GetDisplay_queryNumOfConnectedDisplays
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    enumDisplayIds
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dhk_io_GetDisplay_enumDisplayIds
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    queryDisplayOrientation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dhk_io_GetDisplay_queryDisplayOrientation
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
