/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_EnumDisplayIds */

#ifndef _Included_com_dhk_io_EnumDisplayIds
#define _Included_com_dhk_io_EnumDisplayIds
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhk_io_EnumDisplayIds
 * Method:    queryNumOfConnectedDisplays
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dhk_io_EnumDisplayIds_queryNumOfConnectedDisplays
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_EnumDisplayIds
 * Method:    enumDisplayIds
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dhk_io_EnumDisplayIds_enumDisplayIds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
