/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_DisplayEventNotifier */

#ifndef _Included_com_dhk_io_DisplayEventNotifier
#define _Included_com_dhk_io_DisplayEventNotifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhk_io_DisplayEventNotifier
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_DisplayEventNotifier_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_DisplayEventNotifier
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dhk_io_DisplayEventNotifier_nativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
