/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dhk_io_GetDisplay */

#ifndef _Included_com_dhk_io_GetDisplay
#define _Included_com_dhk_io_GetDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    enumDisplayModes
 * Signature: (Ljava/lang/String;)[Ljava/awt/DisplayMode;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dhk_io_GetDisplay_enumDisplayModes
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    queryDisplayOrientations
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_dhk_io_GetDisplay_queryDisplayOrientations
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    enumVisibleDisplayIds
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dhk_io_GetDisplay_enumVisibleDisplayIds
  (JNIEnv *, jobject);

/*
 * Class:     com_dhk_io_GetDisplay
 * Method:    getSupportedDpiScalePercentages
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dhk_io_GetDisplay_getSupportedDpiScalePercentages
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
