remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Display Hot Keys
description: Instantly apply display resolution, bit depth, refresh rate, scaling mode, and DPI scale percentage with user-defined hot keys.
