remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Display Hot Keys
description: Instantly apply display resolution, bit depth, refresh rate, scaling mode, DPI scale percentage, and orientation with user-defined hot keys!
