RootPane.background = #2675bf
TitlePane.centerTitle = true
TitlePane.showIcon = false
TitlePane.foreground = #ffffff
TitlePane.inactiveForeground = #ffffff
TitlePane.closeHoverBackground = #ab3e00
TitlePane.closePressedBackground = #a33b00
TitlePane.buttonHoverBackground = #008c3a
TitlePane.buttonPressedBackground = #008537
TitlePane.font = "Roboto"
defaultFont = 14 "Roboto"

Component.arc = 12
Button.arc = 12

ScrollBar.thumbArc = 6
ScrollBar.width = 16
ScrollBar.thumbInsets = 2,2,2,2
ScrollBar.track = #f2f2f2
ScrollBar.pressedTrackColor = #f2f2f2
ScrollBar.hoverTrackColor =

ComboBox.buttonStyle = button
ComboBox.background = #ffffff
ComboBox.popupBackground = #ffffff
ComboBox.editableBackground = #ffffff
ComboBox.focusedBackground = #ffffff
ComboBox.buttonBackground = #ffffff
ComboBox.buttonEditableBackground = #ffffff
ComboBox.buttonFocusedBackground = #ffffff
ComboBox.selectionBackground = #2675bf
