RootPane.background = #4b6eaf
TitlePane.centerTitle = true
TitlePane.showIcon = false
TitlePane.foreground = #d5dddd
TitlePane.inactiveForeground = #d5dddd
TitlePane.closeHoverBackground = #ab3e00
TitlePane.closePressedBackground = #a33b00
TitlePane.buttonHoverBackground = #008c3a
TitlePane.buttonPressedBackground = #008537
TitlePane.font = "Roboto"
defaultFont = 14 "Roboto"

Component.arc = 12
Button.arc = 12

ScrollBar.thumbArc = 6
ScrollBar.width = 16
ScrollBar.thumbInsets = 2,2,2,2
ScrollBar.track = #3e4244
ScrollBar.pressedTrackColor = #3e4244
ScrollBar.hoverTrackColor =

ComboBox.buttonStyle = button
ComboBox.background = #4e5052
ComboBox.popupBackground = #4e5052
ComboBox.editableBackground = #4e5052
ComboBox.focusedBackground = #4e5052
ComboBox.buttonBackground = #4e5052
ComboBox.buttonEditableBackground = #4e5052
ComboBox.buttonFocusedBackground = #4e5052
ComboBox.selectionBackground = #4b6eaf

Panel.background = #3d4042
PopupMenu.background = #3d4042
